static_pages
w33shizushizu33w/e-learning-system pull request #1
Opened 2021-08-05 09:22 UTC by w33shizushizu33w

[Commands]
1.  bundle install 
2.  rails s
[Pre-conditions]
1.) N/A

[Expected Output]
1.) can see homepage and other static pages.

[Notes]
1.)

2021-08-05 09:41 UTC, JakeGiangan requested changes
for the following files:
`public/about.webp`
`public/home.webp`
`public/home_imag.jpg`
`public/home_pic.webp`

please move them to the following folder: `app/assets/images`

2021-08-05 09:41 UTC, JakeGiangan commented on config/routes.rb
> +  get "/contact" => "static_pages#contact"
please create a proper `_header.html.erb` inside the `layouts` so it will be easier to access the other pages

2021-08-05 09:41 UTC, JakeGiangan commented on app/views/static_pages/about.html.erb
> +      <img src="home_imag.jpg" width="220" height="150">
please change this code to the following:
`<%= image_tag ("home_imag.jpg", width: 220, height: 150) %>`

2021-08-05 09:41 UTC, JakeGiangan commented on app/views/static_pages/home.html.erb
> +         src="home_pic.webp" width="500" height="300">
please change this code to the following:
`<%= image_tag ("home_pic.webp", width: 500, height: 300) %>`

2021-08-05 09:41 UTC, JakeGiangan commented on app/views/static_pages/about.html.erb
> +    <img src="about.webp">
please change this code to the following:
`<%= image_tag ("about.webp", style:"18rem;", class: "col-4") %>`

2021-08-05 09:41 UTC, JakeGiangan commented on app/views/static_pages/contact.html.erb
> +  <img class="d-block mx-auto" src="home.webp" width="500" height="300">
please change this code to the following:
`<%= image_tag ("home.webp", width: 500, height: 300, class:"d-block mx-auto") %>`

2021-08-05 09:43 UTC, JakeGiangan requested changes

2021-08-05 09:43 UTC, JakeGiangan commented on app/views/static_pages/about.html.erb
> +<div class="jumbotron mt-4 alert alert-light offset-md-2 col-md-8 offset-md-2">
please add this line:
`<% provide(:title, "About Us") %>`

2021-08-05 09:43 UTC, JakeGiangan commented on app/views/static_pages/contact.html.erb
> +<div class="jumbotron mt-4 alert alert-info offset-md-2 col-md-8 offset-md-2">
please add this line:
`<% provide(:title, "Contact Us") %>`

2021-08-05 09:43 UTC, JakeGiangan commented on app/views/static_pages/home.html.erb
> + <div class="jumbotron mt-4 alert alert-warning offset-md-2 col-md-8 offset-md-2">
please add this line:
`<% provide(:title, "Home") %>`

2021-08-07 06:06 UTC, w33shizushizu33w commented
[Commands]
1. rails g controller users new
2. rails g model user name:string email:string password_digest:string
3. rails db:migrate
4. bundle install
5. rails db:migrate:reset
6. rails server
[Pre-conditions]
1.) N/A
[Expected Output]
1.) can see sign up, log in & logout page and  working logout button/function.

[Notes]
1.)

2021-08-07 07:40 UTC, merged